### ISSUE TITLE
모든 포스트 조회 기능

### ISSUE THREAD

**Issue by cbinarycastle** [depromeet-clipping/clipping-server#3]

**Comment by anomie7** [comment]
GetAllPostsResponse에 getter가 없어서 컨트롤러에서 값을 리턴해주지 못해서 추가했습니다. 
근데 제가 이 기능에 해당하는 브런치에 추가하지 않고..develop 브런치에 바로 커밋해버렸네요..ㅠ

**Comment by cbinarycastle** [comment]
아아ㅋㅋㅋㅋ 알겠습니다 참고할께요 ~!
